kind: pipeline
name: default

steps:
- name: build
  image: python
  commands:
  - pip install -r requirements.txt
- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: u_docker
    password: 
      from_secret: p_docker
    repo: karllevans/drone-docker
    auto_tag: true
- name: publish
  image: athieriot/artifactory
  settings:
    url: https://harnesstx.jfrog.io
    username: robin.elliott@harness.io
    password: 354iGXfzzh!%!liG
    repo_key: demo-apps
    group_id: com.harnesstx 
    artifact_id: awesome-lib
    version: 1.0-SNAPSHOT
    files:
      - target/drone-docker
