kind: pipeline
name: default
steps:
- name: build
  image: python
  commands:
  - pip install -r requirements.txt
- name: docker  
  image: plugins/docker
  settings:
    username: robin.elliott@harness.io
    password: Blqrq9SCsr1Pv0uS
    repo: harnesstx.jfrog.io/demo-apps
    registry: harnesstx.jfrog.io
