kind: pipeline
name: default

steps:
- name: build
  image: python
  commands:
  - pip install -r requirements.txt
- name: publish
  image: athieriot/drone-artifactory
  settings:
    url: https://harnesstx.jfrog.io/demo-apps
    username: robin.elliott@harness.io
    password: 354iGXfzzh!%!liG    
- name: my custom plugin
  image: luisredda/drone-simple-plugin
  settings:
    action: deploy
    project: myproject
    runtime: go111
    functions:
      - Function1:
        - trigger: http
          memory: 2048MB
          allow_unauthenticated: true
          environment:
            - ENV_VAR: env_var_value_123
      - Function2:
        - trigger: topic
          trigger_resource: "projects/myproject/topics/mytopic"
          memory: 512MB
      - Function3:
        - trigger: http
          memory: 512MB
          runtime: python37
          source: ./python/src/functions/
